/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OrgRouteImport } from './routes/_org'
import { Route as OrgIndexRouteImport } from './routes/_org/index'
import { Route as OrderTokenRouteImport } from './routes/order.$token'
import { Route as OrgSettingsRouteRouteImport } from './routes/_org/settings/route'
import { Route as OrgSettingsIndexRouteImport } from './routes/_org/settings/index'
import { Route as OrgProductsIndexRouteImport } from './routes/_org/products/index'
import { Route as OrgProductionIndexRouteImport } from './routes/_org/production/index'
import { Route as OrgOrdersIndexRouteImport } from './routes/_org/orders/index'
import { Route as OrgCustomersIndexRouteImport } from './routes/_org/customers/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as OrgSettingsProductionStagesRouteImport } from './routes/_org/settings/production-stages'
import { Route as OrgSettingsGeneralRouteImport } from './routes/_org/settings/general'
import { Route as OrgProductsNewRouteImport } from './routes/_org/products/new'
import { Route as OrgOrdersNewRouteImport } from './routes/_org/orders/new'
import { Route as OrgCustomersNewRouteImport } from './routes/_org/customers/new'
import { Route as OrgProductsIdIndexRouteImport } from './routes/_org/products/$id/index'
import { Route as OrgOrdersIdIndexRouteImport } from './routes/_org/orders/$id/index'
import { Route as OrgCustomersIdIndexRouteImport } from './routes/_org/customers/$id/index'
import { Route as OrgProductsIdEditRouteImport } from './routes/_org/products/$id/edit'
import { Route as OrgOrdersIdEditRouteImport } from './routes/_org/orders/$id/edit'
import { Route as OrgCustomersIdEditRouteImport } from './routes/_org/customers/$id/edit'
import { Route as ApiDocumentsOrdersIdQuotationRouteImport } from './routes/api/documents/orders/$id/quotation'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/_org',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIndexRoute = OrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgRoute,
} as any)
const OrderTokenRoute = OrderTokenRouteImport.update({
  id: '/order/$token',
  path: '/order/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSettingsRouteRoute = OrgSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgRoute,
} as any)
const OrgSettingsIndexRoute = OrgSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSettingsRouteRoute,
} as any)
const OrgProductsIndexRoute = OrgProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => OrgRoute,
} as any)
const OrgProductionIndexRoute = OrgProductionIndexRouteImport.update({
  id: '/production/',
  path: '/production/',
  getParentRoute: () => OrgRoute,
} as any)
const OrgOrdersIndexRoute = OrgOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => OrgRoute,
} as any)
const OrgCustomersIndexRoute = OrgCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => OrgRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSettingsProductionStagesRoute =
  OrgSettingsProductionStagesRouteImport.update({
    id: '/production-stages',
    path: '/production-stages',
    getParentRoute: () => OrgSettingsRouteRoute,
  } as any)
const OrgSettingsGeneralRoute = OrgSettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => OrgSettingsRouteRoute,
} as any)
const OrgProductsNewRoute = OrgProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => OrgRoute,
} as any)
const OrgOrdersNewRoute = OrgOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => OrgRoute,
} as any)
const OrgCustomersNewRoute = OrgCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => OrgRoute,
} as any)
const OrgProductsIdIndexRoute = OrgProductsIdIndexRouteImport.update({
  id: '/products/$id/',
  path: '/products/$id/',
  getParentRoute: () => OrgRoute,
} as any)
const OrgOrdersIdIndexRoute = OrgOrdersIdIndexRouteImport.update({
  id: '/orders/$id/',
  path: '/orders/$id/',
  getParentRoute: () => OrgRoute,
} as any)
const OrgCustomersIdIndexRoute = OrgCustomersIdIndexRouteImport.update({
  id: '/customers/$id/',
  path: '/customers/$id/',
  getParentRoute: () => OrgRoute,
} as any)
const OrgProductsIdEditRoute = OrgProductsIdEditRouteImport.update({
  id: '/products/$id/edit',
  path: '/products/$id/edit',
  getParentRoute: () => OrgRoute,
} as any)
const OrgOrdersIdEditRoute = OrgOrdersIdEditRouteImport.update({
  id: '/orders/$id/edit',
  path: '/orders/$id/edit',
  getParentRoute: () => OrgRoute,
} as any)
const OrgCustomersIdEditRoute = OrgCustomersIdEditRouteImport.update({
  id: '/customers/$id/edit',
  path: '/customers/$id/edit',
  getParentRoute: () => OrgRoute,
} as any)
const ApiDocumentsOrdersIdQuotationRoute =
  ApiDocumentsOrdersIdQuotationRouteImport.update({
    id: '/api/documents/orders/$id/quotation',
    path: '/api/documents/orders/$id/quotation',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof OrgIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/settings': typeof OrgSettingsRouteRouteWithChildren
  '/order/$token': typeof OrderTokenRoute
  '/customers/new': typeof OrgCustomersNewRoute
  '/orders/new': typeof OrgOrdersNewRoute
  '/products/new': typeof OrgProductsNewRoute
  '/settings/general': typeof OrgSettingsGeneralRoute
  '/settings/production-stages': typeof OrgSettingsProductionStagesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/customers/': typeof OrgCustomersIndexRoute
  '/orders/': typeof OrgOrdersIndexRoute
  '/production/': typeof OrgProductionIndexRoute
  '/products/': typeof OrgProductsIndexRoute
  '/settings/': typeof OrgSettingsIndexRoute
  '/customers/$id/edit': typeof OrgCustomersIdEditRoute
  '/orders/$id/edit': typeof OrgOrdersIdEditRoute
  '/products/$id/edit': typeof OrgProductsIdEditRoute
  '/customers/$id/': typeof OrgCustomersIdIndexRoute
  '/orders/$id/': typeof OrgOrdersIdIndexRoute
  '/products/$id/': typeof OrgProductsIdIndexRoute
  '/api/documents/orders/$id/quotation': typeof ApiDocumentsOrdersIdQuotationRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/order/$token': typeof OrderTokenRoute
  '/': typeof OrgIndexRoute
  '/customers/new': typeof OrgCustomersNewRoute
  '/orders/new': typeof OrgOrdersNewRoute
  '/products/new': typeof OrgProductsNewRoute
  '/settings/general': typeof OrgSettingsGeneralRoute
  '/settings/production-stages': typeof OrgSettingsProductionStagesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/customers': typeof OrgCustomersIndexRoute
  '/orders': typeof OrgOrdersIndexRoute
  '/production': typeof OrgProductionIndexRoute
  '/products': typeof OrgProductsIndexRoute
  '/settings': typeof OrgSettingsIndexRoute
  '/customers/$id/edit': typeof OrgCustomersIdEditRoute
  '/orders/$id/edit': typeof OrgOrdersIdEditRoute
  '/products/$id/edit': typeof OrgProductsIdEditRoute
  '/customers/$id': typeof OrgCustomersIdIndexRoute
  '/orders/$id': typeof OrgOrdersIdIndexRoute
  '/products/$id': typeof OrgProductsIdIndexRoute
  '/api/documents/orders/$id/quotation': typeof ApiDocumentsOrdersIdQuotationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_org': typeof OrgRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_org/settings': typeof OrgSettingsRouteRouteWithChildren
  '/order/$token': typeof OrderTokenRoute
  '/_org/': typeof OrgIndexRoute
  '/_org/customers/new': typeof OrgCustomersNewRoute
  '/_org/orders/new': typeof OrgOrdersNewRoute
  '/_org/products/new': typeof OrgProductsNewRoute
  '/_org/settings/general': typeof OrgSettingsGeneralRoute
  '/_org/settings/production-stages': typeof OrgSettingsProductionStagesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_org/customers/': typeof OrgCustomersIndexRoute
  '/_org/orders/': typeof OrgOrdersIndexRoute
  '/_org/production/': typeof OrgProductionIndexRoute
  '/_org/products/': typeof OrgProductsIndexRoute
  '/_org/settings/': typeof OrgSettingsIndexRoute
  '/_org/customers/$id/edit': typeof OrgCustomersIdEditRoute
  '/_org/orders/$id/edit': typeof OrgOrdersIdEditRoute
  '/_org/products/$id/edit': typeof OrgProductsIdEditRoute
  '/_org/customers/$id/': typeof OrgCustomersIdIndexRoute
  '/_org/orders/$id/': typeof OrgOrdersIdIndexRoute
  '/_org/products/$id/': typeof OrgProductsIdIndexRoute
  '/api/documents/orders/$id/quotation': typeof ApiDocumentsOrdersIdQuotationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/settings'
    | '/order/$token'
    | '/customers/new'
    | '/orders/new'
    | '/products/new'
    | '/settings/general'
    | '/settings/production-stages'
    | '/api/auth/$'
    | '/customers/'
    | '/orders/'
    | '/production/'
    | '/products/'
    | '/settings/'
    | '/customers/$id/edit'
    | '/orders/$id/edit'
    | '/products/$id/edit'
    | '/customers/$id/'
    | '/orders/$id/'
    | '/products/$id/'
    | '/api/documents/orders/$id/quotation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/order/$token'
    | '/'
    | '/customers/new'
    | '/orders/new'
    | '/products/new'
    | '/settings/general'
    | '/settings/production-stages'
    | '/api/auth/$'
    | '/customers'
    | '/orders'
    | '/production'
    | '/products'
    | '/settings'
    | '/customers/$id/edit'
    | '/orders/$id/edit'
    | '/products/$id/edit'
    | '/customers/$id'
    | '/orders/$id'
    | '/products/$id'
    | '/api/documents/orders/$id/quotation'
  id:
    | '__root__'
    | '/_org'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/_org/settings'
    | '/order/$token'
    | '/_org/'
    | '/_org/customers/new'
    | '/_org/orders/new'
    | '/_org/products/new'
    | '/_org/settings/general'
    | '/_org/settings/production-stages'
    | '/api/auth/$'
    | '/_org/customers/'
    | '/_org/orders/'
    | '/_org/production/'
    | '/_org/products/'
    | '/_org/settings/'
    | '/_org/customers/$id/edit'
    | '/_org/orders/$id/edit'
    | '/_org/products/$id/edit'
    | '/_org/customers/$id/'
    | '/_org/orders/$id/'
    | '/_org/products/$id/'
    | '/api/documents/orders/$id/quotation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  OrgRoute: typeof OrgRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  OrderTokenRoute: typeof OrderTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDocumentsOrdersIdQuotationRoute: typeof ApiDocumentsOrdersIdQuotationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_org': {
      id: '/_org'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_org/': {
      id: '/_org/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof OrgIndexRouteImport
      parentRoute: typeof OrgRoute
    }
    '/order/$token': {
      id: '/order/$token'
      path: '/order/$token'
      fullPath: '/order/$token'
      preLoaderRoute: typeof OrderTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_org/settings': {
      id: '/_org/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof OrgSettingsRouteRouteImport
      parentRoute: typeof OrgRoute
    }
    '/_org/settings/': {
      id: '/_org/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof OrgSettingsIndexRouteImport
      parentRoute: typeof OrgSettingsRouteRoute
    }
    '/_org/products/': {
      id: '/_org/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof OrgProductsIndexRouteImport
      parentRoute: typeof OrgRoute
    }
    '/_org/production/': {
      id: '/_org/production/'
      path: '/production'
      fullPath: '/production/'
      preLoaderRoute: typeof OrgProductionIndexRouteImport
      parentRoute: typeof OrgRoute
    }
    '/_org/orders/': {
      id: '/_org/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrgOrdersIndexRouteImport
      parentRoute: typeof OrgRoute
    }
    '/_org/customers/': {
      id: '/_org/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof OrgCustomersIndexRouteImport
      parentRoute: typeof OrgRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_org/settings/production-stages': {
      id: '/_org/settings/production-stages'
      path: '/production-stages'
      fullPath: '/settings/production-stages'
      preLoaderRoute: typeof OrgSettingsProductionStagesRouteImport
      parentRoute: typeof OrgSettingsRouteRoute
    }
    '/_org/settings/general': {
      id: '/_org/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof OrgSettingsGeneralRouteImport
      parentRoute: typeof OrgSettingsRouteRoute
    }
    '/_org/products/new': {
      id: '/_org/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof OrgProductsNewRouteImport
      parentRoute: typeof OrgRoute
    }
    '/_org/orders/new': {
      id: '/_org/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof OrgOrdersNewRouteImport
      parentRoute: typeof OrgRoute
    }
    '/_org/customers/new': {
      id: '/_org/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof OrgCustomersNewRouteImport
      parentRoute: typeof OrgRoute
    }
    '/_org/products/$id/': {
      id: '/_org/products/$id/'
      path: '/products/$id'
      fullPath: '/products/$id/'
      preLoaderRoute: typeof OrgProductsIdIndexRouteImport
      parentRoute: typeof OrgRoute
    }
    '/_org/orders/$id/': {
      id: '/_org/orders/$id/'
      path: '/orders/$id'
      fullPath: '/orders/$id/'
      preLoaderRoute: typeof OrgOrdersIdIndexRouteImport
      parentRoute: typeof OrgRoute
    }
    '/_org/customers/$id/': {
      id: '/_org/customers/$id/'
      path: '/customers/$id'
      fullPath: '/customers/$id/'
      preLoaderRoute: typeof OrgCustomersIdIndexRouteImport
      parentRoute: typeof OrgRoute
    }
    '/_org/products/$id/edit': {
      id: '/_org/products/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof OrgProductsIdEditRouteImport
      parentRoute: typeof OrgRoute
    }
    '/_org/orders/$id/edit': {
      id: '/_org/orders/$id/edit'
      path: '/orders/$id/edit'
      fullPath: '/orders/$id/edit'
      preLoaderRoute: typeof OrgOrdersIdEditRouteImport
      parentRoute: typeof OrgRoute
    }
    '/_org/customers/$id/edit': {
      id: '/_org/customers/$id/edit'
      path: '/customers/$id/edit'
      fullPath: '/customers/$id/edit'
      preLoaderRoute: typeof OrgCustomersIdEditRouteImport
      parentRoute: typeof OrgRoute
    }
    '/api/documents/orders/$id/quotation': {
      id: '/api/documents/orders/$id/quotation'
      path: '/api/documents/orders/$id/quotation'
      fullPath: '/api/documents/orders/$id/quotation'
      preLoaderRoute: typeof ApiDocumentsOrdersIdQuotationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrgSettingsRouteRouteChildren {
  OrgSettingsGeneralRoute: typeof OrgSettingsGeneralRoute
  OrgSettingsProductionStagesRoute: typeof OrgSettingsProductionStagesRoute
  OrgSettingsIndexRoute: typeof OrgSettingsIndexRoute
}

const OrgSettingsRouteRouteChildren: OrgSettingsRouteRouteChildren = {
  OrgSettingsGeneralRoute: OrgSettingsGeneralRoute,
  OrgSettingsProductionStagesRoute: OrgSettingsProductionStagesRoute,
  OrgSettingsIndexRoute: OrgSettingsIndexRoute,
}

const OrgSettingsRouteRouteWithChildren =
  OrgSettingsRouteRoute._addFileChildren(OrgSettingsRouteRouteChildren)

interface OrgRouteChildren {
  OrgSettingsRouteRoute: typeof OrgSettingsRouteRouteWithChildren
  OrgIndexRoute: typeof OrgIndexRoute
  OrgCustomersNewRoute: typeof OrgCustomersNewRoute
  OrgOrdersNewRoute: typeof OrgOrdersNewRoute
  OrgProductsNewRoute: typeof OrgProductsNewRoute
  OrgCustomersIndexRoute: typeof OrgCustomersIndexRoute
  OrgOrdersIndexRoute: typeof OrgOrdersIndexRoute
  OrgProductionIndexRoute: typeof OrgProductionIndexRoute
  OrgProductsIndexRoute: typeof OrgProductsIndexRoute
  OrgCustomersIdEditRoute: typeof OrgCustomersIdEditRoute
  OrgOrdersIdEditRoute: typeof OrgOrdersIdEditRoute
  OrgProductsIdEditRoute: typeof OrgProductsIdEditRoute
  OrgCustomersIdIndexRoute: typeof OrgCustomersIdIndexRoute
  OrgOrdersIdIndexRoute: typeof OrgOrdersIdIndexRoute
  OrgProductsIdIndexRoute: typeof OrgProductsIdIndexRoute
}

const OrgRouteChildren: OrgRouteChildren = {
  OrgSettingsRouteRoute: OrgSettingsRouteRouteWithChildren,
  OrgIndexRoute: OrgIndexRoute,
  OrgCustomersNewRoute: OrgCustomersNewRoute,
  OrgOrdersNewRoute: OrgOrdersNewRoute,
  OrgProductsNewRoute: OrgProductsNewRoute,
  OrgCustomersIndexRoute: OrgCustomersIndexRoute,
  OrgOrdersIndexRoute: OrgOrdersIndexRoute,
  OrgProductionIndexRoute: OrgProductionIndexRoute,
  OrgProductsIndexRoute: OrgProductsIndexRoute,
  OrgCustomersIdEditRoute: OrgCustomersIdEditRoute,
  OrgOrdersIdEditRoute: OrgOrdersIdEditRoute,
  OrgProductsIdEditRoute: OrgProductsIdEditRoute,
  OrgCustomersIdIndexRoute: OrgCustomersIdIndexRoute,
  OrgOrdersIdIndexRoute: OrgOrdersIdIndexRoute,
  OrgProductsIdIndexRoute: OrgProductsIdIndexRoute,
}

const OrgRouteWithChildren = OrgRoute._addFileChildren(OrgRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  OrgRoute: OrgRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  OrderTokenRoute: OrderTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDocumentsOrdersIdQuotationRoute: ApiDocumentsOrdersIdQuotationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
